spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: hello
    password: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  sql:
    init:
      platform: postgres

logging:
  level:
    org.hibernate.SQL: debug

