spring:
  datasource:
#    url: jdbc:postgresql://localhost:5435/postgres
    url: jdbc:postgresql://172.30.1.49:5435/postgres
    username: hello
    password: local

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  sql:
    init:
      platform: postgres

  thymeleaf:
    enabled: true
    prefix: classpath:templates/
    suffix: .html
    cache: false

security:
  jwt:
    token:
      secret-key: accessKey
      refresh-key: refreshKey


